// Stage 1 — Ratings.
// Joins the verified data/groups.json with the sourced FIFA ranking snapshot
// and emits data/teams.json.
//
// RANK BASIS (single source of truth):
//  - fieldRank : 1..48, the team's rank WITHIN this 48-team field by FIFA points.
//                PRIMARY everywhere (sim, UI, narration). "14th-best in this field"
//                is meaningful; a global "#82 of 48" reads as a broken bracket.
//  - worldRank : the global FIFA/Coca-Cola world rank (out of ~210). Carried only as
//                flavor and must ALWAYS be shown labeled "world #N" / "FIFA #N".
//
// Honesty notes:
//  - Team list + flag codes come ONLY from data/groups.json (verified ground truth).
//  - Ratings come ONLY from pipeline/sources/fifa-rankings-2026-04-01.json (cited there).
//  - "strength" is the rating the simulation consumes; FIFA's post-2018 ranking is
//    Elo-based, so its points are used directly (no rescale).

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const RANKINGS_FILE = join(import.meta.dirname, 'sources', 'fifa-rankings-2026-04-01.json');

const groupsDoc = JSON.parse(readFileSync(join(ROOT, 'data', 'groups.json'), 'utf8'));
const rankings = JSON.parse(readFileSync(RANKINGS_FILE, 'utf8'));

const byName = new Map(rankings.teams.map((t) => [t.name, t])); // name -> { rank, points }

const teams = [];
const missing = [];
const usedNames = new Set();

for (const group of groupsDoc.groups) {
  for (const t of group.teams) {
    const r = byName.get(t.name);
    if (!r) {
      missing.push(`${t.name} (group ${group.id})`);
      continue;
    }
    usedNames.add(t.name);
    teams.push({
      name: t.name,
      code: t.code,
      group: group.id,
      fieldRank: 0, // assigned below
      worldRank: r.rank, // global FIFA rank — flavor only, always label "world #N"
      fifaPoints: r.points,
      strength: r.points, // used directly as an Elo-scale rating
    });
  }
}

// Field rank: 1..48 by FIFA points (descending).
[...teams]
  .sort((a, b) => b.fifaPoints - a.fifaPoints)
  .forEach((t, i) => {
    t.fieldRank = i + 1;
  });

// Validation — fail loudly rather than silently shipping a hole.
const errors = [];
if (teams.length !== 48) errors.push(`expected 48 teams, got ${teams.length}`);
if (missing.length) errors.push(`no ranking found for: ${missing.join(', ')}`);
const unused = rankings.teams.map((t) => t.name).filter((n) => !usedNames.has(n));
if (unused.length) errors.push(`ranking entries not matched to any group team: ${unused.join(', ')}`);
if (errors.length) {
  console.error('rateTeams.js FAILED:\n - ' + errors.join('\n - '));
  process.exit(1);
}

const points = teams.map((t) => t.fifaPoints);
const out = {
  note: 'GENERATED by pipeline/rateTeams.js — do not edit by hand. Team list + flag codes are from data/groups.json; ratings are from pipeline/sources/fifa-rankings-2026-04-01.json.',
  ratingSource: rankings.source,
  ratingSnapshot: rankings.release,
  ratingRetrieved: rankings.retrievedOn,
  rankBasis:
    'fieldRank (1-48) is the primary rank used everywhere; worldRank is the global FIFA rank, shown only as flavor and always labeled "world #N".',
  normalization:
    "strength = official FIFA ranking points, used directly. FIFA's post-2018 ranking is Elo-based, so the points already lie on an Elo-like scale (~1280-1880); no rescaling. The logistic match-model divisor (Stage 2) provides the win-probability calibration.",
  sources: rankings.sources,
  teams,
};

writeFileSync(join(ROOT, 'data', 'teams.json'), JSON.stringify(out, null, 2) + '\n');

// Console summary (sorted by field rank).
const sorted = [...teams].sort((a, b) => a.fieldRank - b.fieldRank);
console.log(`\nFIFA ranking snapshot: ${rankings.release} (retrieved ${rankings.retrievedOn})`);
console.log(
  `Teams: ${teams.length}/48   points ${Math.min(...points)} -> ${Math.max(...points)} (spread ${(Math.max(...points) - Math.min(...points)).toFixed(2)})\n`,
);
console.log('  field  world  pts       grp  team');
sorted.forEach((t) => {
  console.log(
    `   #${String(t.fieldRank).padStart(2)}   #${String(t.worldRank).padStart(3)}   ${t.fifaPoints.toFixed(2).padStart(7)}   ${t.group}    ${t.name}`,
  );
});
console.log('\nWrote data/teams.json');
